markdown:    kramdown
exclude:     ['README.md', vendor]
username:    LaputanMachines
repo:        LaputanMachines.github.io
branch:      master
title:       Michael Bassili's Programming Portfolio
author:      Michael Bassili
url:         https://code.bassi.li
keywords:    "Michael Bassili, programming portfolio, personal projects, programmer, software developer, game developer"
description: Howdy! This is the programming portfolio for Michael Bassili! Here, you can see the code I've written and the projects I've taken on!
source:      .
destination: _site
highlighter: rouge
linenos:     true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-watch

jekyll_admin:
  hidden_links:
    - datafiles

highlight:
  linenos: true

highlight_options:
  linenos: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
